### ISSUE TITLE
Running the example in usage.py results in Error loading layout 

### ISSUE THREAD

**Issue by RWulff** [plotly/dash-table-experiments#1]
The error is TypeError: keys must be a string
 
Complete trace:

<pre>
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1994, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\flask\app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\dash\dash.py", line 146, in class_decorator
**kwargs
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\dash\authentication.py", line 61, in create_requires_auth
return f(*args, **kwargs)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\dash\dash.py", line 204, in serve_layout
cls=plotly.utils.PlotlyJSONEncoder),
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\json\__init__.py", line 238, in dumps
**kw).encode(obj)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\plotly\utils.py", line 136, in encode
encoded_o = super(PlotlyJSONEncoder, self).encode(o)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\simplejson\encoder.py", line 291, in encode
chunks = self.iterencode(o, _one_shot=True)
File "C:\Users\WulffR\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Lib\site-packages\simplejson\encoder.py", line 373, in iterencode
return _iterencode(o, 0)
TypeError: keys must be a string
</pre>

Any suggestions? Thank you very much :)

**Comment by chriddyp** [comment]
Thanks for reporting! Python 3 issue... Looking into it.

**Comment by chriddyp** [comment]
```
In [4]: df = pd.DataFrame({
   ...:     'Column 1': [1, 2, 3],
   ...:     'Column 2': [1, 19, 10],
   ...:     'Column 3': [3, 1, 2],
   ...: })

In [5]: df.to_dict()
Out[5]:
{'Column 1': {0: 1, 1: 2, 2: 3},
 'Column 2': {0: 1, 1: 19, 2: 10},
 'Column 3': {0: 3, 1: 1, 2: 2}}

In [6]: import json

In [7]: json.dumps(df.to_dict())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-b00d8fd95a0f> in <module>()
----> 1 json.dumps(df.to_dict())

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    228         cls is None and indent is None and separators is None and
    229         default is None and not sort_keys and not kw):
--> 230         return _default_encoder.encode(obj)
    231     if cls is None:
    232         cls = JSONEncoder

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py in encode(self, o)
    196         # exceptions aren't as detailed.  The list call should be roughly
    197         # equivalent to the PySequence_Fast that ''.join() would do.
--> 198         chunks = self.iterencode(o, _one_shot=True)
    199         if not isinstance(chunks, (list, tuple)):
    200             chunks = list(chunks)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py in iterencode(self, o, _one_shot)
    254                 self.key_separator, self.item_separator, self.sort_keys,
    255                 self.skipkeys, _one_shot)
--> 256         return _iterencode(o, 0)
    257
    258 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be a string
```

Dang, that's annoying!

**Comment by chriddyp** [comment]
For now, you can replace with `dataframe=json.loads(df.to_json())`

**Comment by frogger72** [comment]
I'm running into the same issue when using datetimes for my columns.  You could just drop in jsonpickle instead of json - there is a built-in option to support non-string keys.
